-- Per-request detail (proxy_used, account_label) for request_logs is added via
-- ensureColumn() in db.go, not here: migrations replay on every boot, and
-- ALTER TABLE ADD COLUMN is not idempotent (it errors if the column exists).
-- This file is intentionally a no-op.
